# **Pertemuan 9 - Discrete Random Variables 1**

Introduction to Probability Course - Sekolah Data - Pacmann Academy

**Outline**

1. Review Discrete Random Variables 1
2. Case 1 - Transaksi di Restoran
3. Case 2 - Sum of Two Dice

In [2]:
import os
import sys
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)

In [3]:
# load data
import pandas as pd
import numpy as np
import itertools
import random

from src.module_python_proba_9 import playground_pelemparan_dadu

from tabulate import tabulate

## **Review Topik**
---

Dari materi yang sudah dipelajari di video:

- Kita bisa menggunakan conditional probability dalam variable random dengan menggunakan conditional PMF
- Kita bisa menggunakan conditional expectation jika ingin mencari expectation di variable random di kondisi tertentu
- Kita bisa mencari total expectation variable random X dari conditional expectation $\text{E}[X|A_i]$
- Jika ingin mengetahui peluang bersama dari lebih 1 variabel random, kita bisa gunakan joint pmf

## **Case Stude 1: Transaksi di Restoran**
___

- Conditional PMF & Conditional Expectation
- Joint and Marginal PMF

Sebuah Restoran ingin menagnalisis data 1000 transaksi. Tujuannya mereka ingin mengetahui bagaimana perilaku pelanggannya dalam memesan menu makanan dan minuman.

### Data

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=5>Minuman</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>0</th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=5><b>Makanan</b></td>
            <td>0</td>
            <td>0</td>
            <td>10</td>
            <td>55</td>
            <td>10</td>
            <td>5</td>
        </tr>
        <tr>
            <td>1</td>
            <td>5</td>
            <td>10</td>
            <td>45</td>
            <td>20</td>
            <td>10</td>
        </tr>
        <tr>
            <td>2</td>
            <td>3</td>
            <td>30</td>
            <td>100</td>
            <td>50</td>
            <td>47</td>
        </tr>
        <tr>
            <td>3</td>
            <td>0</td>
            <td>30</td>
            <td>50</td>
            <td>160</td>
            <td>130</td>
        </tr>
        <tr>
            <td>4</td>
            <td>0</td>
            <td>20</td>
            <td>58</td>
            <td>52</td>
            <td>100</td>
        </tr>
    </tbody>
</table>

Data tersebut memuat 1000 transaksi yang masing masing mempunya detail banyak porsi makanan/minuman yang dipesan, misalnya:
- Terdapat 160 transaksi yang memesan 3 porsi makanan dan 3 minuman
- Terdapat 3 transaksi yang memesan hanya 2 minuman

### **Pertanyaan 1.**

Jika diketahui restoran hanya bisa melayani maksimal 3 porsi makanan, berapa peluang ada 2 porsi yang dipesan per transaksinya?

- Disini kita ingin mengetahui hanya transaksi makanan saja, jadi distribusi transaksi makanan bisa didapatkan jika kita menjumlahkan banyak traksaksi per nilai porsi makanan

<table>
<tr>
  <th>Data Transaksi Makanan & Minuman</th>
  <th>Data Transaksi Makanan </th>
</tr>
<tr><td>
  <table>
      <thead>
          <tr>
              <th></th>
              <th colspan=6>Minuman</th>
          </tr>
          <tr>
              <th></th>
              <th></th>
              <th>0</th>
              <th>1</th>
              <th>2</th>
              <th>3</th>
              <th>4</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td rowspan=5><b>Makanan</b></td>
              <td>0</td>
              <td>0</td>
              <td>10</td>
              <td>55</td>
              <td>10</td>
              <td>5</td>
          </tr>
          <tr>
              <td>1</td>
              <td>5</td>
              <td>10</td>
              <td>45</td>
              <td>20</td>
              <td>10</td>
          </tr>
          <tr>
              <td>2</td>
              <td>3</td>
              <td>30</td>
              <td>100</td>
              <td>50</td>
              <td>47</td>
          </tr>
          <tr>
              <td>3</td>
              <td>0</td>
              <td>30</td>
              <td>50</td>
              <td>160</td>
              <td>130</td>
          </tr>
          <tr>
              <td>4</td>
              <td>0</td>
              <td>20</td>
              <td>58</td>
              <td>52</td>
              <td>100</td>
          </tr>
      </tbody>
  </table>
</td><td>


<table>
    <thead>
        <tr>
            <th></th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>Transaksi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=6><b>Makanan</b></td>
            <td>0</td>
            <td>80</td>
        </tr>
        <tr>
            <td>1</td>
            <td>90</td>
        </tr>
        <tr>
            <td>2</td>
            <td>230</td>
        </tr>
        <tr>
            <td>3</td>
            <td>370</td>
        </tr>
        <tr>
            <td>4</td>
            <td>230</td>
        </tr>
        <tr>
            <td><b>Total</b></td>
            <td>1000</td>
        </tr>
    </tbody>
</table>
</td></tr> </table>

- Misalkan banyak porsi makanan adalah variable random $X$ dimana $X=\{0,1,2,3,4\}$, maka bisa kita tuliskan seperti ini
<table>
    <thead>
        <tr>
            <th></th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>Transaksi</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=6><b>X</b></td>
            <td>0</td>
            <td>80</td>
        </tr>
        <tr>
            <td>1</td>
            <td>90</td>
        </tr>
        <tr>
            <td>2</td>
            <td>230</td>
        </tr>
        <tr>
            <td>3</td>
            <td>370</td>
        </tr>
        <tr>
            <td>4</td>
            <td>230</td>
        </tr>
        <tr>
            <td><b>Total</b></td>
            <td>1000</td>
        </tr>
    </tbody>
</table>


- Yang ditanyakan adalah peluang porsi makanan X adalah 2 jika diketahui porsi makanan yang bisa disediakan maksimal, 3 $X\leq3$
$$\text{P}(X=2|X\leq3)$$
- Bisa dicari dengan

$$\text{P}(X=2|X\leq3)=\frac{\text{P}(X=2 \cap X\leq3)}{\text{P}(X\leq3)}$$

- Mari kita hitung satu per satu 
##### 1. Cari  $P(X\leq3)$ 
  - Data transaksi makanan jika hanya bisa melayani maksimal 3 porsi, $X\leq3$ 
      <table>
          <thead>
              <tr>
                  <th></th>
              </tr>
              <tr>
                  <th></th>
                  <th></th>
                  <th>Transaksi</th>
              </tr>
          </thead>
          <tbody>
              <tr>
                  <td rowspan=5><b>X</b></td>
                  <td>0</td>
                  <td>80</td>
              </tr>
              <tr>
                  <td>1</td>
                  <td>90</td>
              </tr>
              <tr>
                  <td>2</td>
                  <td>230</td>
              </tr>
              <tr>
                  <td>3</td>
                  <td>370</td>
              </tr>
              <tr>
                  <td><b>Total</b></td>
                  <td>770</td>
              </tr>
          </tbody>
      </table>

$$\text{P}(X\leq3)=\frac{\text{n(transaksi yang memesan kurang dari 3 porsi)}}{\text{n(total transaksi)}}=0.77$$


$$\text{P}(X\leq3)=\frac{770}{1000}=0.77$$

##### 2. Cari $\text{P}(X=2 \cap X\leq3)$
   - Irisan dari $X=2$ dan $X\leq3$ adalah $X=2$
   - $\text{P}(X=2 \cap X\leq3)=\text{P}(X=2)$
   - maka cukup mencari X=2

$$\text{P}(X=2)=\frac{\text{n(transaksi yang memesan 2 porsi)}}{\text{n(total transaksi)}}$$


$$\text{P}(X=2)=\frac{230}{1000}=0.23$$

##### 3. Cari $\text{P}(X=2|X\leq3)$


$$\text{P}(X=2|X\leq3)=\frac{0.23}{0.77}=0.299$$

- Atau bisa juga dengan mencari berapa banyak transaksi 2 porsi makanan = 230, dibagi dengan banyak transaksi kurang atau sama dengan 3 porsi

$$\text{P}(X=2|X\leq3)=\frac{\text{n(transaksi yang memesan 2 porsi)}}{\text{n(transaksi yang pesan kurang atau sama dengan 3 porsi)}}$$

$$\text{P}(X=2|X\leq3)=\frac{230}{770}$$

### Exercise

1. Jika diketahui restoran hanya bisa melayani maksimal 3 porsi makanan, berapa peluang ada 1 porsi yang dipesan per transaksinya?

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
# Mencari P(X=1|X<=3)

90/770
```

</details>

---

2. Peluang porsi makanan X adalah 2 jika diketahui porsi minuman yang dipesan 4 porsi

$$\text{P}(X=2|Y=4)$$

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python

47/(5+10+47+130+100)
#0.047/(0.005+0.01+0.047+0.13+0.1)

```

</details>

---

3. Peluang porsi makanan X adalah 2 jika diketahui porsi minuman yang dipesan lebih dari 2 porsi

$$\text{P}(X=2|Y>2)$$

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python

$P(X=2,Y>2)$

0.05+0.047

$P(Y>2) = P(Y=3)+P(Y=4)$

0.01+0.005+0.02+0.01+0.05+0.047+0.13+0.16+0.052+0.1

$$\text{P}(X=2|Y>2)$$

(0.05+0.047)/(0.01+0.005+0.02+0.01+0.05+0.047+0.13+0.16+0.052+0.1)

```

</details>

---

4. Peluang porsi minuman yang dipesan sama dengan 2 porsi

$$\text{P}(Y=2)$$

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python

$P(Y=2) = P(X=0,Y=2)+P(X=1,Y=2)+P(X=2,Y=2)+P(X=3,Y=2)+P(X=4,Y=2)$

0.055+0.045+0.1+0.05+0.058

```

</details>

---

5. Peluang porsi minuman yang dipesan lebih dari 2 porsi

$$\text{P}(Y>2)$$

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python

(10+5+20+10+50+47+160+130+52+100)/1000

```

</details>

---

6. Peluang porsi minuman yang dipesan sama dengan 2 porsi jika diketahui porsi makanan yang dipesan 4 porsi

$$\text{P}(Y=2|X=4)$$

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
0.058/(0+0.02+0.058+0.052+0.1)

```

</details>

---

7. Peluang porsi minuman yang dipesan sama dengan 2 porsi jika diketahui porsi minuman yang dipesan kurang dari 2 porsi

$$\text{P}(Y=2|Y<2)$$

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
tidak mungkin terjadi (peluang nya = 0)
```

</details>

---

### **Pertanyaan 2.**

Masih di kondisi yang sama, jika diketahui restoran hanya bisa melayani maksimal 3 porsi, berapa ekpektasi porsi yang dipesan?

- Eksektasi porsi yang dipesan jika hanya melayani maksimal 3 porsi
- Hitung Conditional PMF $P(X=x|X\leq3)$ 
  - Data transaksi makanan jika hanya bisa melayani maksimal 3 porsi, $X\leq3$ dan conditional PMF nya
      <table>
          <thead>
              <tr>
                  <th></th>
              </tr>
              <tr>
                  <th></th>
                  <th></th>
                  <th>Transaksi</th>
                  <th>P(X=x|X<=3)</th>
              </tr>
          </thead>
          <tbody>
              <tr>
                  <td rowspan=5><b>X</b></td>
                  <td>0</td>
                  <td>80</td>
                  <td>0.104</td>
              </tr>
              <tr>
                  <td>1</td>
                  <td>90</td>
                  <td>0.117</td>
              </tr>
              <tr>
                  <td>2</td>
                  <td>230</td>
                  <td>0.299</td>
              </tr>
              <tr>
                  <td>3</td>
                  <td>370</td>
                  <td>0.481</td>
              </tr>
              <tr>
                  <td><b>Total</b></td>
                  <td>770</td>
                  <td>1</td>
              </tr>
          </tbody>
      </table>

- Hitung Conditional Expectationnya 
$$\text{E}[X|X\leq3]=\sum_ix_ip_{X|X\leq3}(x_i)$$

$\text{E}[X|X\leq3]=(0\times0.104)+(1\times0.117)+(2\times0.299)+(3\times0.481)$

$\text{E}[X|X\leq3]=2.158$

### **Pertanyaan 3.**

Berapa peluang porsi makanan yang dipesan sama dengan minuman?

- Untuk mencari peluang ini kita perlu tahu peluang bersama ketika makanan dipesan dengan minuman
- Kita kembali ke data awal

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=5>Minuman</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>0</th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=5><b>Makanan</b></td>
            <td>0</td>
            <td>0</td>
            <td>10</td>
            <td>55</td>
            <td>10</td>
            <td>5</td>
        </tr>
        <tr>
            <td>1</td>
            <td>5</td>
            <td>10</td>
            <td>45</td>
            <td>20</td>
            <td>10</td>
        </tr>
        <tr>
            <td>2</td>
            <td>3</td>
            <td>30</td>
            <td>100</td>
            <td>50</td>
            <td>47</td>
        </tr>
        <tr>
            <td>3</td>
            <td>0</td>
            <td>30</td>
            <td>50</td>
            <td>160</td>
            <td>130</td>
        </tr>
        <tr>
            <td>4</td>
            <td>0</td>
            <td>20</td>
            <td>58</td>
            <td>52</td>
            <td>100</td>
        </tr>
    </tbody>
</table>

- Dari data tersebut cari peluang bersama atau joint PMF nya

##### 1. Joint PMF
- Misalkan banyak porsi makanan adalah variable random $X$ dimana $X=\{0,1,2,3,4\}$, dan $Y$ adalah banyak minuman yang dipesan maka bisa kita tuliskan seperti ini joint PMF dari X dan Y
- Joint PMF $p_{X,Y}(x,y)$ didapatkan dari frekuensi kemunculan bersama dibagi dengan total transaksi yaitu 1000
<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=7>Y</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>0</th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=5><b>X</b></td>
            <td>0</td>
            <td>0</td>
            <td>0.01</td>
            <td>0.055</td>
            <td>0.01</td>
            <td>0.005</td>
        </tr>
        <tr>
            <td>1</td>
            <td>0.005</td>
            <td>0.01</td>
            <td>0.045</td>
            <td>0.02</td>
            <td>0.01</td>
        </tr>
        <tr>
            <td>2</td>
            <td>0.003</td>
            <td>0.03</td>
            <td>0.1</td>
            <td>0.05</td>
            <td>0.047</td>
        </tr>
        <tr>
            <td>3</td>
            <td>0</td>
            <td>0.03</td>
            <td>0.05</td>
            <td>0.16</td>
            <td>0.13</td>
        </tr>
        <tr>
            <td>4</td>
            <td>0</td>
            <td>0.02</td>
            <td>0.058</td>
            <td>0.052</td>
            <td>0.1</td>
        </tr>
    </tbody>
</table>

##### 2. Cari peluang ketika X=Y

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=5>Y</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>0</th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=5><b>X</b></td>
            <td>0</td>
            <td><mark>0</mark></td>
            <td>0.01</td>
            <td>0.055</td>
            <td>0.01</td>
            <td>0.005</td>
        </tr>
        <tr>
            <td>1</td>
            <td>0.005</td>
            <td><mark>0.01</mark></td>
            <td>0.045</td>
            <td>0.02</td>
            <td>0.01</td>
        </tr>
        <tr>
            <td>2</td>
            <td>0.003</td>
            <td>0.03</td>
            <td><mark>0.1</mark></td>
            <td>0.05</td>
            <td>0.047</td>
        </tr>
        <tr>
            <td>3</td>
            <td>0</td>
            <td>0.03</td>
            <td>0.05</td>
            <td><mark>0.16</mark></td>
            <td>0.13</td>
        </tr>
        <tr>
            <td>4</td>
            <td>0</td>
            <td>0.02</td>
            <td>0.058</td>
            <td>0.052</td>
            <td><mark>0.1</mark></td>
        </tr>
    </tbody>
</table>

##### 3. Hitung jumlahan peluang ketika X=Y
$\text{P}(X=Y)=\text{P}(X=0,Y=0)+\text{P}(X=1,Y=1)+\text{P}(X=2,Y=2)+\text{P}(X=3,Y=3)+\text{P}(X=4,Y=4)$

  $\text{P}(X=Y)=0.01+0.1+0.16+0.1$

  $\text{P}(X=Y)=0.37$

### **Pertanyaan 4.**

Restoran tersebut ingin mengetahui mana yang lebih disukai memesan lebih banyak menu minuman atau menu makanan?

- Hitung peluang banyak porsi makanan lebih banyak dari porsi minuman yang dipesan
- Hitung peluang banyak porsi makanan lebih sedikit dari porsi minuman yang dipesan
- Bandingkan keduanya

##### 1. Hitung peluang P(X>Y)

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=5>Y</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>0</th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=5><b>X</b></td>
            <td>0</td>
            <td>0</td>
            <td>0.01</td>
            <td>0.055</td>
            <td>0.01</td>
            <td>0.005</td>
        </tr>
        <tr>
            <td>1</td>
            <td><mark>0.005</mark></td>
            <td>0.01</td>
            <td>0.045</td>
            <td>0.02</td>
            <td>0.01</td>
        </tr>
        <tr>
            <td>2</td>
            <td><mark>0.003</mark></td>
            <td><mark>0.03</mark></td>
            <td>0.1</td>
            <td>0.05</td>
            <td>0.047</td>
        </tr>
        <tr>
            <td>3</td>
            <td><mark>0</mark></td>
            <td><mark>0.03</mark></td>
            <td><mark>0.05</mark></td>
            <td>0.16</td>
            <td>0.13</td>
        </tr>
        <tr>
            <td>4</td>
            <td><mark>0</mark></td>
            <td><mark>0.02</mark></td>
            <td><mark>0.058</mark></td>
            <td><mark>0.052</mark></td>
            <td>0.1</td>
        </tr>
    </tbody>
</table>

$\text{P}(X>Y)=0.005+0.003+0.03+0.03+0.05+0.02+0.058+0.052+0.1$

$\text{P}(X>Y)=0.248$

#####  2. Hitung peluang (X<Y)

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=5>Y</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>0</th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=5><b>X</b></td>
            <td>0</td>
            <td>0</td>
            <td><mark>0.01</mark></td>
            <td><mark>0.055</mark></td>
            <td><mark>0.01</mark></td>
            <td><mark>0.005</mark></td>
        </tr>
        <tr>
            <td>1</td>
            <td>0.005</td>
            <td>0.01</td>
            <td><mark>0.045</mark></td>
            <td><mark>0.02</mark></td>
            <td><mark>0.01</mark></td>
        </tr>
        <tr>
            <td>2</td>
            <td>0.003</td>
            <td>0.03</td>
            <td>0.1</td>
            <td><mark>0.05</mark></td>
            <td><mark>0.047</mark></td>
        </tr>
        <tr>
            <td>3</td>
            <td>0</td>
            <td>0.03</td>
            <td>0.05</td>
            <td>0.16</td>
            <td><mark>0.13</mark></td>
        </tr>
        <tr>
            <td>4</td>
            <td>0</td>
            <td>0.02</td>
            <td>0.058</td>
            <td>0.052</td>
            <td>0.1</td>
        </tr>
    </tbody>
</table>

$\text{P}(X<Y)=0.01+0.0055+0.01+0.005+0.045+0.02+0.01+0.05+0.047+0.13$

$\text{P}(X<Y)=0.382$

  ##### Kesimpulan 

  - Ternyata pengunjung lebih suka memesan minuman lebih banyak dari porsi makanan
  - Mungkin saja tempatnya cocok dibuat ngopi santai, sehingga tidak banyak yang memesan makanan

### Exercise

1. Berapa peluang pengunjung memesan 3 porsi makanan dan 2 minuman?

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
# Mencari P(X=3,Y=2)
0.05
```

</details>

---

## **Case Stude 1: Sum of Two Dice**
___

- Expectation of Multiple Random Variable

- Misal kita melempar **dua** dadu bermata 6 Secara Bersamaan

<img src="https://imgix2.ruangguru.com/assets/miscellaneous/jpg_7jaczf_4578.jpg" width=200> -- Dadu pertama

<img src="https://static7.depositphotos.com/1001759/733/i/600/depositphotos_7339064-stock-photo-red-and-white-dice.jpg" width=150> -- Dadu kedua

- Ditanya, berapa ekspektasi jumlah angka mata dadu yang keluar dari 2 dadu tersebut?

- Kita misalkan:
  - X adalah variable random yang menyatakan angka mata dadu 1, $X ={1,2,3,4,5,6}$
  - Y adalah variable random yang menyatakan angka mata dadu 2, $Y ={1,2,3,4,5,6}$

---
**Pendekatan 1 - Simulasi**
- Untuk menjawabnya, kita bisa melakukan simulasi dengan cara melemparkan 2 dadu tersebut berkali-kali
- Hitung Joint PMF dari simulasi
- Hitung ekspektasinya

In [ ]:
playground_pelemparan_dadu()

Masukkan Jumlah Pelemparan:

interactive(children=(SelectionSlider(continuous_update=False, description='jumlah:', options=(10, 100, 500, 1…

---
**Pendekatan 2 - Mengunakan Formula Expected Rule**
- Selain menggunakan simulasi, kita bisa langsung mencari dengan nilai peluang analitis keluarnya angka dari 2 dadu masing masing punya peluang yang sama yaitu 1/36

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=6>Y</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=6><b>X</b></td>
            <td>1</td>
            <td>(1,1)</td>
            <td>(1,2)</td>
            <td>(1,3)</td>
            <td>(1,4)</td>
            <td>(1,5)</td>
            <td>(1,6)</td>
        </tr>
        <tr>
            <td>2</td>
            <td>(2,1)</td>
            <td>(2,2)</td>
            <td>(2,3)</td>
            <td>(2,4)</td>
            <td>(2,5)</td>
            <td>(2,6)</td>
        </tr>
        <tr>
            <td>3</td>
            <td>(3,1)</td>
            <td>(3,2)</td>
            <td>(3,3)</td>
            <td>(3,4)</td>
            <td>(3,5)</td>
            <td>(3,6)</td>
        </tr>
        <tr>
            <td>4</td>
            <td>(4,1)</td>
            <td>(4,2)</td>
            <td>(4,3)</td>
            <td>(4,4)</td>
            <td>(4,5)</td>
            <td>(4,6)</td>
        </tr>
        <tr>
            <td>5</td>
            <td>(5,1)</td>
            <td>(5,2)</td>
            <td>(5,3)</td>
            <td>(5,4)</td>
            <td>(5,5)</td>
            <td>(5,6)</td>
        </tr>
        <tr>
            <td>6</td>
            <td>(6,1)</td>
            <td>(6,2)</td>
            <td>(6,3)</td>
            <td>(6,4)</td>
            <td>(6,5)</td>
            <td>(6,6)</td>
        </tr>
    </tbody>
</table>

- Selanjutnya kita cari jumlahan dari kedua mata dadu

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=6>Y</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=6><b>X</b></td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
        </tr>
        <tr>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
        </tr>
        <tr>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
        </tr>
        <tr>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
        </tr>
        <tr>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
            <td>11</td>
        </tr>
        <tr>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
            <td>11</td>
            <td>12</td>
        </tr>
    </tbody>
</table>

- misalkan Z adalah jumlah X+Y
- distribusi peluang Z adalah

|Z|Frek Muncul|P(Z=z)|
|-|--------------------|------|
|2|1|1/36|
|3|2|2/36|
|4|3|3/36|
|5|4|4/36|
|6|5|5/36|
|7|6|6/36|
|8|5|5/36|
|9|4|4/36|
|10|3|3/36|
|11|2|2/36|
|12|1|1/36|

- Ekspected Value dari Z

  $\text{E}[Z]=\sum_izp_Z(z)$

  $\text{E}[Z]=(2×1/36)+(3×2/36)+...+(12×1/36)$

  $\text{E}[Z]=7$

- Atau bisa juga dengan cara seperti ini (Cara Lain)

  <table>
      <thead>
          <tr>
              <th></th>
              <th colspan=6>Y</th>
          </tr>
          <tr>
              <th></th>
              <th></th>
              <th>1</th>
              <th>2</th>
              <th>3</th>
              <th>4</th>
              <th>5</th>
              <th>6</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td rowspan=6><b>X</b></td>
              <td>1</td>
              <td>2</td>
              <td>3</td>
              <td>4</td>
              <td>5</td>
              <td>6</td>
              <td>7</td>
          </tr>
          <tr>
              <td>2</td>
              <td>3</td>
              <td>4</td>
              <td>5</td>
              <td>6</td>
              <td>7</td>
              <td>8</td>
          </tr>
          <tr>
              <td>3</td>
              <td>4</td>
              <td>5</td>
              <td>6</td>
              <td>7</td>
              <td>8</td>
              <td>9</td>
          </tr>
          <tr>
              <td>4</td>
              <td>5</td>
              <td>6</td>
              <td>7</td>
              <td>8</td>
              <td>9</td>
              <td>10</td>
          </tr>
          <tr>
              <td>5</td>
              <td>6</td>
              <td>7</td>
              <td>8</td>
              <td>9</td>
              <td>10</td>
              <td>11</td>
          </tr>
          <tr>
              <td>6</td>
              <td>7</td>
              <td>8</td>
              <td>9</td>
              <td>10</td>
              <td>11</td>
              <td>12</td>
          </tr>
      </tbody>
  </table>

- hitung joint PMF dan jumlahan X+Y

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=6>Y</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=6><b>X</b></td>
            <td>1</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
        </tr>
        <tr>
            <td>2</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
        </tr>
        <tr>
            <td>3</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
        </tr>
        <tr>
            <td>4</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
        </tr>
        <tr>
            <td>5</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
        </tr>
        <tr>
            <td>6</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
            <td>1/36</td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=6>Y</th>
        </tr>
        <tr>
            <th></th>
            <th></th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=6><b>X</b></td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
        </tr>
        <tr>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
        </tr>
        <tr>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
        </tr>
        <tr>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
        </tr>
        <tr>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
            <td>11</td>
        </tr>
        <tr>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
            <td>11</td>
            <td>12</td>
        </tr>
    </tbody>
</table>

- Ekspected Value dari Z

  $\text{E}[Z]=\sum_ig(x,y)p_{X,Y}(x,y)$

  $\text{E}[g(X,Y)]=(2×1/36)+(3×1/36)+(3×1/36)...+(12×1/36)$

  $\text{E}[X+Y]=7$

---
**Pendekatan 3 (Bonus) - Ada yang bisa tebak?**

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

$$\text{E}[Z] = \text{E}[X+Y]$$
- Berdasarkan linearity of expectation (lihat video materi 8)

$$\text{E}[Z] = \text{E}[X]+\text{E}[Y]$$

- Ekspektasi keluar nya angka mata dadu dari 1 dadu adalah 3.5

  $\text{E}[X]=(1×\frac{1}{6})+(2×\frac{1}{6})+(3×\frac{1}{6})+...+(6×\frac{1}{6})$

  $\text{E}[X]=3.5$

  $\text{E}[X] = \text{E}[Y]$

  $\text{E}[Z] = \text{E}[X] + \text{E}[Y]$

  $\text{E}[Z] = 3.5+3.5$

  $\text{E}[Z] = 7$
```python

```

</details>

---